name: Weekly Volume 1 Promo

on:
  schedule:
    - cron: '0 16 * * 1'  # Every Monday at 12 PM EST / 4 PM UTC
  workflow_dispatch:      # Allow manual trigger from GitHub UI

jobs:
  post-volume-1-promo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install openai requests python-dotenv

      - name: Run promo script
        env:
          CONVERTKIT_LINK: ${{ secrets.CONVERTKIT_LINK }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          FACEBOOK_PAGE_TOKEN: ${{ secrets.FACEBOOK_PAGE_TOKEN }}
          FACEBOOK_PAGE_ID: ${{ secrets.FACEBOOK_PAGE_ID }}
        run: |
          python post_volume1_promo.py
